### ISSUE TITLE
Feedback for “安装 ComfyUI”

### ISSUE THREAD

**Issue by Bluelulu99-1** [6174/comflowy#10]
请问执行“pip install -r requirements.txt”后未出现「Successfully installed XXXXX」，全是“Requirement already satisfied”该怎么办
![截屏2024-01-04 11 31 02](https://github.com/6174/comflowy/assets/155598189/7fffc3b6-16cd-401c-a62b-0ac6a5f4032b)

**Comment by 6174** [comment]
这是在说都满足条件了，不需要再重复安装了

**Comment by thinkingjimmy** [comment]
感谢反馈，已 fixed: https://github.com/6174/comflowy/commit/73fbcd010e53ec1a0ee8e68e4fafe20291af022b
