### ISSUE TITLE
修改文档表述

### ISSUE THREAD

**Issue by rockboom** [6174/comflowy#107]
This is about:
- [ ] A typo 
- [x] Innaccurate/misleading documentation (e.g. technically incorrect advice)
- [ ] Undocumented code
- [ ] Outdated documentation
- [ ] Other

**Problem**

<img width="1047" alt="image" src="https://github.com/6174/comflowy/assets/23214721/6a3bd7fd-3f18-468a-b68a-98a01f306ba2">

这这种方式有很什么好处了？

**Details about the solution you'd like** _(Optional)_
这种方式有什么好处呢？
**Additional context** _(Optional)_

**Comment by thinkingjimmy** [comment]
感谢提醒，已修复
