### ISSUE TITLE
Feedback for “ComfyUI 基础 ➀”

### ISSUE THREAD

**Issue by fansanqiu** [6174/comflowy#11]
https://arc.net/l/quote/bpzhtxns
可调整为，可以更好的对应
Checkpoint 包含了三个部分：MODEL、CLIP 还有 VAE

https://arc.net/l/quote/rwvxzyhl
补充一段
CLIP的英文全称是Contrastive Language-Image Pre-training，即基于文本-图像的预训练。

**Comment by thinkingjimmy** [comment]
感谢反馈，已 fixed: 73fbcd010e53ec1a0ee8e68e4fafe20291af022b

我看你提了蛮多建议的，或者你后续可以直接提 PR？
