### ISSUE TITLE
Feedback for “Comflowy FAQ”

### ISSUE THREAD

**Issue by xuchuang12** [6174/comflowy#112]
clone comfyui error: Command failed with exit code 128: git clone https://github.com/comfyanonymous/ComfyUI.git Cloning into 'ComfyUI'... fatal: unable to access 'https://github.com/comfyanonymous/ComfyUI.git/': SSL certificate problem: unable to get local issuer certificate
<img width="898" alt="屏幕截图 2024-05-26 160300" src="https://github.com/6174/comflowy/assets/68317072/77c9b673-623e-4e2c-9064-946750d32b61">

**Comment by thinkingjimmy** [comment]
Are you in China？It's probably a network problem.
