### ISSUE TITLE
Feedback for “云端安装 ComfyUI”

### ISSUE THREAD

**Issue by lys623** [6174/comflowy#12]
请教个问题，云端安装好后，怎么暴露openapi，给自己的另一个应用调用生成图片，然后返回图片信息呢？

**Comment by 6174** [comment]
comfyui 会有个 submit prompt 接口提交新的流程运行请求，然后通过 websocket 接口监听进展情况。 你可以在运行 comfyui 后打开控制台看看这两个接口的参数。

**Comment by lys623** [comment]
![image](https://github.com/6174/comflowy/assets/4364314/7f36c3a3-9584-4f75-b3ab-5c521cbb494c)
这太多参数了😂

**Comment by 6174** [comment]
我们后面会提供优化版开源的 comfyui, 会直接集成api ，可以关注一下

**Comment by lys623** [comment]
> 我们后面会提供优化版开源的 comfyui, 会直接集成api ，可以关注一下

这个有规划什么时候出第一版吗？
