### ISSUE TITLE
Feedback for “Stable Diffusion 进阶”

### ISSUE THREAD

**Issue by lys623** [6174/comflowy#14]
是否可以把每个页面事例的workflow粘贴到页面底部？这样方便大家下载跑起来

**Comment by thinkingjimmy** [comment]
感谢建议，后续我们会补充。目前你可以试试我们的新产品：https://www.comflowy.com/zh-CN/space

里面内置了我的所有教程 workflow。下载链接：https://github.com/6174/comflowyspace/releases/tag/v0.0.1-alpha

**Comment by lys623** [comment]
🙏
