### ISSUE TITLE
Mini3conda 安装失败.

### ISSUE THREAD

**Issue by xiaoliwe** [6174/comflowy#15]
This is about:
- [x ] ComfyUI installation
- [ ] Text to image workflow
- [ ] Image to image workflow
- [ ] Text to video workflow
- [ ] Other

**Problem**

**Steps To Reproduce**
<img width="646" alt="Screenshot 2024-01-18 at 09 46 44" src="https://github.com/6174/comflowy/assets/9930176/7afae4f6-d967-43a1-9d71-be52590fc9c1">

**Expected behavior**

**Screenshots**

**Environment:**
 - ComfyUI or Comflowyspace version: 0.0.1
 - OS, macOS

**Comment by thinkingjimmy** [comment]
感谢反馈，我们目前正在修复这个问题。

**Comment by thinkingjimmy** [comment]
Hello，我们已经修复了这个问题。可以下载我们最新的 0.0.2 版本：https://github.com/6174/comflowyspace/releases/tag/v0.0.2-alpha

**Comment by xiaoliwe** [comment]
好的，具体是什么原因？

**Comment by 6174** [comment]
@xiaoliwe  其一是因为 Node 层的 Fetch 服务没有用到 systemproxy, 其二是 Download File 调用的代码有逻辑错误
