### ISSUE TITLE
有个错别字

### ISSUE THREAD

**Issue by jackcheng321321** [6174/comflowy#17]
![image](https://github.com/6174/comflowy/assets/122415449/2c8b056c-c8dc-45d0-be42-a88b68edf5a9)
应该是按照惯例吧，顺便表扬一句，原理都解释的挺好的，非常容易理解

**Comment by thinkingjimmy** [comment]
感谢支持，fixed ea49bab73aab6deb7a9f1fa1abb28f6e92372456
