### ISSUE TITLE
Feedback for “ContrlNet”  这两个的路经好像有点问题

### ISSUE THREAD

**Issue by jackcheng321321** [6174/comflowy#18]
![image](https://github.com/6174/comflowy/assets/122415449/bb3d231a-e81d-4588-a92a-8c1f261bad07)
路经好像有点问题，下载之后是基础模型，不是controlnet

**Comment by thinkingjimmy** [comment]
我看了下链接，应该是对的，它模型是 safetensors 格式的。不是基础模型。这个是模型的下载文件夹https://huggingface.co/lllyasviel/sd-controlnet-openpose/tree/main

**Comment by jackcheng321321** [comment]
但是这两个链接点开下载的是同一个文件，也是正常的吗？
