### ISSUE TITLE
Feedback for “下载 & 导入模型”

### ISSUE THREAD

**Issue by lys623** [6174/comflowy#20]
![image](https://github.com/6174/comflowy/assets/4364314/5cc0161c-bb0d-49d0-b67e-a6ef9a83dc57)
一般是怎么判断一个模型应该放在哪个目录里的？

**Comment by thinkingjimmy** [comment]
一般你下载模型的时候都会标注这个是什么类型的模型，比如 C 站会标注在这，我们后续会增加一个模型推荐板块。将模型类型，和适用场景都标注清楚。
<img width="439" alt="image" src="https://github.com/6174/comflowy/assets/37492595/53439548-3ad1-4e08-a3e2-f5af033e6259">
