### ISSUE TITLE
Cant install it

### ISSUE THREAD

**Issue by Tobe2d** [6174/comflowy#25]
I get stuck on error in both ways, 

If I select i have comfyui installed or if I say I am new  i get the following error:

`Task failed: PyTorch installation failed: Command failed with exit code 1: C:\tools\Miniconda3\envs\comflowy\Scripts\pip.exe install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121 The system cannot find the path specified.`

![image](https://github.com/6174/comflowy/assets/4099839/f21d5cc9-6f99-43fb-b918-d2f2734be16f)

And please note that I do it already installed as When I check  pip show torch in windows terminal:
https://github.com/pypa/pip/issues/12330
Name: torch
Version: 2.1.2+cu118
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: C:\Python311\Lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, lpips, peft, torchaudio, torchvision

And when I check in anaconda prompt pip show torch

```
pip show torch
Name: torch
Version: 2.2.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\ammar\anaconda3\lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision
```

**Comment by 6174** [comment]
Hi @Tobe2d , can you check two things:

1. If there is pip exist on path `C:\tools\Miniconda3\envs\comflowy\Scripts\pip.exe`, the error logs show that there is not a pip in the path

2. Is your own anaconda in System PATH?  We will check if there is already `conda`  in user's system, if not then we will install miniconda.

**Comment by 6174** [comment]
Fixed at: https://github.com/6174/comflowyspace/commit/28ac435238e342c2ddea9bf938b3a127187cfedb

**Comment by Tobe2d** [comment]
Thanks for the reply @6174 

How can I update to this version? I havent found new release installer 
The latest release is still V0.0.5-alpha

**Comment by 6174** [comment]
@Tobe2d we will release it at V0.0.6-alpha on next week

**Comment by thinkingjimmy** [comment]
@Tobe2d We've released a new version that fixes this issue: https://github.com/6174/comflowyspace/releases/tag/v0.0.6-alpha

**Comment by Tobe2d** [comment]
Awesome! I will test it shortly thanks for the update @thinkingjimmy

**Comment by Tobe2d** [comment]
I am sorry to report that the problem havent been solved:

![image](https://github.com/6174/comflowy/assets/4099839/97913b75-7d31-4865-803e-4529ae8fec7c)


PyTorch installation failed: Command failed with exit code 1: C:\tools\Miniconda3\envs\comflowy\Scripts\pip.exe install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121 The system cannot find the path specified.

**Comment by 6174** [comment]
@Tobe2d can you open your powershell in windows , and execute this command 
```shell
echo $env:CONDA_PREFIX
```

Comflowy detect where conda exist by use this env parameter

**Comment by 6174** [comment]
I already changed the way to get CONDA_PATH in windows, and will recompile a new package, you can test it then :-)

**Comment by Tobe2d** [comment]
> I already changed the way to get CONDA_PATH in windows, and will recompile a new package, you can test it then :-)
> 
> Update: I upload the fixed exe program here, you can download to test: https://www.dropbox.com/scl/fi/ml05yydlmzp3t68z5fhnh/comflowy-setup-0.0.6-alpha.exe.zip?rlkey=qylrauutqiirxuzirs62d718j&dl=0

This works without any issue!! thanks a lot.

Finaly I can test it ;-)
