### ISSUE TITLE
ComflowySpace 安装问题

### ISSUE THREAD

**Issue by godofworks** [6174/comflowy#26]
您好，ComflowySpace 安装过程，卡死在下图这一步了。请问该怎么办？
之前使用的comfy UI是秋叶的一键安装包，使用正常。
![屏幕截图 2024-02-04 212037](https://github.com/6174/comflowy/assets/159000490/314da9fe-ed61-46d0-b404-36406211bd44)
请百忙中给予回复，谢谢！（“少数派”网站上也有留言：https://sspai.com/post/85704）

**Comment by 6174** [comment]
@godofworks  这个问题已经在 0.0.6 版本解决了，预期明天会发布

**Comment by godofworks** [comment]
谢谢！期待新版本

**Comment by thinkingjimmy** [comment]
@godofworks  我们发布了新的版本，你可以安装试试：https://github.com/6174/comflowyspace/releases/tag/v0.0.6-alpha

**Comment by godofworks** [comment]
谢谢！我前天安装了0.0.7版，但启动时总会出现下面这个窗口，不知是什么原因？
![屏幕截图 2024-02-18 104953](https://github.com/6174/comflowy/assets/159000490/b0bc121f-04a9-48c4-adb9-4df0666c3cbd)

**Comment by 6174** [comment]
这个问题估计是之前安装没有安装完成就退出了，导致一些 python 包没有安装成功，你试试点这里的 update 按钮，会重新安装相关的包

**Comment by 6174** [comment]
看上去挺奇怪的，这里报错是部分包没有安装成功，可能是之前退出了，Pip install 能够解决，你 install 后重启每次报错都是 `yaml` 模块找不到吗？ (就是报错都是一样的吗？)

以及看看能否把这个界面更前面的信息截图下来，帮助 debug

**Comment by godofworks** [comment]
对，install 后重启每次报错都是 yaml 模块找不到吗？报错都是一样的。在第二步就出这个报错。
![屏幕截图 2024-02-18 195532](https://github.com/6174/comflowy/assets/159000490/fabfc260-a4fa-44af-8ee5-41f39ba3857f)

**Comment by godofworks** [comment]
刚刚安装了0.0.8版，除之前的报错依旧存在外，在新建流程和使用流程模板时，又有新报错。见图吧

**Comment by 6174** [comment]
0.0.8 版本也还没有解决你的问题，看上去依然还是启动的时候没成功导致超时了，确实很神秘。

**Comment by thinkingjimmy** [comment]
@godofworks Hi，你可以尝试安装我们的最新版本，看看是否还有这个问题。

**Comment by thinkingjimmy** [comment]
因为没有新的反馈，故 issue 关闭。
