### ISSUE TITLE
汉化插件怎么在Comflowy里生效?

### ISSUE THREAD

**Issue by FOnlyJack** [6174/comflowy#27]
This is about:
- [ ] ComfyUI installation
- [ ] Text to image workflow
- [ ] Image to image workflow
- [ ] Text to video workflow
- [ ] Other

**Problem**

**Steps To Reproduce**

Or paste reproducible error codes:

**Expected behavior**

**Screenshots**

**Environment:**
 - ComfyUI or Comflowyspace version: 
 - OS, if relevant: [e.g. MacOS]

**Comment by 6174** [comment]
因为 Comflowyspace 是独立的技术栈，目前只能用 ComfyUI 的 Python 插件，汉化插件涉及到了前端部分所以不支持。 不过我们有计划在 Alpha 版本过后直接支持中文。

**Comment by thinkingjimmy** [comment]
新版本已经支持节点汉化，请升级尝试。
