### ISSUE TITLE
Feedback for “安装 ComfyUI”

### ISSUE THREAD

**Issue by buthule** [6174/comflowy#34]
![屏幕截图 2024-02-27 185644](https://github.com/6174/comflowy/assets/118803704/95f5a23a-b743-4a21-bcd0-79c2de1b67da)
![屏幕截图 2024-02-27 185709](https://github.com/6174/comflowy/assets/118803704/1e8ec3b1-16cb-4c35-a2ee-4a228da04f53)
安装完没有任何界面怎么解决

**Comment by thinkingjimmy** [comment]
按理来说是可以看到界面的，我还没遇到这种情况。是否有可能是被什么防火墙啥的拦截了？

**Comment by bingwei** [comment]
推荐使用秋叶的整合包：https://www.bilibili.com/video/BV1Ew411776J/
下载链接见评论区。

**Comment by thinkingjimmy** [comment]
因为没有新的反馈，故 issue 关闭。
