### ISSUE TITLE
A typo

### ISSUE THREAD

**Issue by batcow04** [6174/comflowy#36]
- [ ] A typo 
There's a typo in this sentence "安装方法两种，如果你之前使用的 VS Code 或 Terminal 安装，另一种是手动导入安装。" on the webpage "**https://www.comflowy.com/zh-CN/preparation-for-study/optional/custom-nodes**" ，it should be 安装方法有两种，一种是你之前使用的 VS Code 或 Terminal 安装，另一种是手动导入安装。

**Comment by thinkingjimmy** [comment]
fixed
