### ISSUE TITLE
button streamlining

### ISSUE THREAD

**Issue by madsteed** [6174/comflowy#37]
<img width="1218" alt="image" src="https://github.com/6174/comflowy/assets/12323248/11ef29c6-8e95-4098-88fe-60d508bbcd29">

我英文不太行，请见谅。如图，多余按钮可以不要，精简到一个按钮，放在右下角的位置，空间更大，操作更简单。

**Comment by thinkingjimmy** [comment]
感谢反馈，我们有计划做精简。
