### ISSUE TITLE
Default "Pose ControlNet workflow" template, the DWPreprocessor did not work

### ISSUE THREAD

**Issue by visionalsky** [6174/comflowy#40]
This is about:
- [ ] ComfyUI installation
- [ ] Text to image workflow
- [x] Image to image workflow
- [ ] Text to video workflow
- [ ] Other

**Problem**

<img width="342" alt="image" src="https://github.com/6174/comflowy/assets/15725901/3348f1b4-621c-46ed-bc45-53c20f2de6e8">

<img width="434" alt="image" src="https://github.com/6174/comflowy/assets/15725901/bfb844bf-9f0f-43c3-8046-2d3ec32d235f">

With default Pose ControlNet workflow,  DWPreprocessor (OpenposePreprocessor the same) did not have required  parameters and did not work.

<img width="692" alt="image" src="https://github.com/6174/comflowy/assets/15725901/bce81707-ef0c-4594-b249-d6bfa0d834e8">

Is there any way to mitigate?

**Steps To Reproduce**

Or paste reproducible error codes:

**Expected behavior**

**Screenshots**

**Environment:**
 - ComfyUI or Comflowyspace version: 
 - OS, if relevant: [e.g. MacOS]

**Comment by 6174** [comment]
Thanks for feedback, I will check this issue :-)

**Comment by thinkingjimmy** [comment]
Since there has been no further response, this issue is being closed.
