### ISSUE TITLE
Feedback for “安装 ComfyUI”

### ISSUE THREAD

**Issue by lisayannnnn** [6174/comflowy#41]
安装Miniconda3是出现这个怎么解决呢？
Miniconda3 will now be installed into this location:
/Users/mac/miniconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

**Comment by thinkingjimmy** [comment]
使用新版本还会出现这个问题吗？

**Comment by thinkingjimmy** [comment]
因为没有新的反馈，故 issue 关闭。
