### ISSUE TITLE
Feedback for “为何要学习 ComfyUI？”

### ISSUE THREAD

**Issue by lzwar** [6174/comflowy#42]
非常感谢您搭建了如此棒的学习平台，在此页面的最后一段，似乎最后一段语句不太通，原段落内容如下：

“如果你看各种对比评测，还会发现 ComfyUI 在性能上会比 SD WebUI 更好，但在能力的覆盖上会比 SD WebUI 要差，比如 ComfyUI 的 Inpainting 的编辑器就比 SD WebUI 的编辑器要差。但是，这些都不是问题，这些问题未来会依托开源生态逐步完善，或者说互有优势。但是我认为不管 SD WebUI 不进行非常大的改变的情况下，是无法实现 ComfyUI 那样的自由度的。”

最后一句您是否想说：但是我认为如果 SD WebUI 不进行非常大的改变的情况下，是无法实现 ComfyUI 那样的自由度的。”

**Comment by bingwei** [comment]
感谢反馈，建议您直接提一个pull requests让作者考虑合入文档

**Comment by thinkingjimmy** [comment]
因为没有新的反馈，故 issue 关闭。
