### ISSUE TITLE
无法启动，卡在 Start ComfyUI (1 / 1)

### ISSUE THREAD

**Issue by zhongyanzhiyan** [6174/comflowy#44]
你好，我安装了目前最新的V0.1.0-alpha版本，我的电脑是Windows11系统，查看Miniconda3已经安装成功了，但就是无法进入软件页面，如下图
![image](https://github.com/6174/comflowy/assets/32254901/c05f9c94-2958-49fb-b7ed-f2cc284af224)

**Comment by zhongyanzhiyan** [comment]
> 还有更多的日志信息吗？还是一直卡在这个地方？

从界面上没有其他提示了，从软件安装目录中没有找到类似log日志的文件。

**Comment by thinkingjimmy** [comment]
@zhongyanzhiyan 可以右上角点击 termianl 看看有没有其他的报错。或者你可以加我的 Discord ：_jimmywong_

**Comment by thinkingjimmy** [comment]
因为没有新的反馈，故 issue 关闭。
