### ISSUE TITLE
ComfyUI Installation Failure

### ISSUE THREAD

**Issue by skywangshipeng** [6174/comflowy#46]
I can not go throw it eventhough restart comflowy many times

<img width="887" alt="image" src="https://github.com/6174/comflowy/assets/42331089/d5e99294-5fc4-43b9-8d0c-1613e9463546">

**Comment by 6174** [comment]
I  think you can try to directly run the command on your computer and restart the app:

```shell
cd ~/comflowy/ComfyUI && ~/miniconda3/envs/comflowy/bin/pip install -r requirements.txt
```
