### ISSUE TITLE
Feedback for “In/Outpainting”

### ISSUE THREAD

**Issue by shallmore** [6174/comflowy#49]
https://www.comflowy.com/zh-CN/advanced/in-out-painting
in this step, I can not call out the Open in MaskEditor function, please check it! Thank you!

**Comment by thinkingjimmy** [comment]
If you are using Comflowy, there is an edit image function after right clicking the image node, which is maskeditor.

**Comment by thinkingjimmy** [comment]
I will modify the corresponding tutorial

**Comment by shallmore** [comment]
Thank you so much!
