### ISSUE TITLE
Feedback for “安装 ComfyUI”

### ISSUE THREAD

**Issue by fansanqiu** [6174/comflowy#5]
建议 cd 到项目文件夹这个位置可以加个代码
`cd ComfyUI` 进入文件夹从文件夹打开

<img width="843" alt="Screenshot 2023-12-31 at 7 28 43 PM" src="https://github.com/6174/comflowy/assets/58503364/ab83f79b-52a2-4e9d-a63d-86c017401d8f">

**Comment by thinkingjimmy** [comment]
Fixed
