### ISSUE TITLE
Does the work interface support Chinese?

### ISSUE THREAD

**Issue by sakiyo18** [6174/comflowy#50]
This is about:
- [ ] ComfyUI installation
- [ ] Text to image workflow
- [ ] Image to image workflow
- [ ] Text to video workflow
- [x] Other

**Problem**

**Steps To Reproduce**

Or paste reproducible error codes:

**Expected behavior**

**Screenshots**

**Environment:**
 - ComfyUI or Comflowyspace version: 
 - OS, if relevant: [e.g. MacOS]

**Comment by thinkingjimmy** [comment]
我们最新版本已经支持节点汉化，可以安装尝试
