### ISSUE TITLE
中文支持仅仅是客户端的几个按钮吗？工作区域的内容依然是英文状态，并且翻译插件无法工作

### ISSUE THREAD

**Issue by sakiyo18** [6174/comflowy#51]
This is about:
- [ ] ComfyUI installation
- [ ] Text to image workflow
- [ ] Image to image workflow
- [ ] Text to video workflow
- [ ] Other

**Problem**

**Steps To Reproduce**

Or paste reproducible error codes:

**Expected behavior**

**Screenshots**

**Environment:**
 - ComfyUI or Comflowyspace version: 
 - OS, if relevant: [e.g. MacOS]

**Comment by bingwei** [comment]
是的。目前大部分还是英文为主。中文版本的插件，目前完成度比较低，并且由于更细速度，中文翻译的速度一般会比较滞后。建议还是以英文为主，中文为辅

**Comment by thinkingjimmy** [comment]
我们会在近期的版本中支持中文

**Comment by sakiyo18** [comment]
> 我们会在近期的�版本中支持中文

非常期待，我很乐意尝试，这个项目的用户体验比原生的要好很多，支持。
