### ISSUE TITLE
Feedback for “Stable Diffusion 基础”

### ISSUE THREAD

**Issue by HeskeyBaozi** [6174/comflowy#52]
![image](https://github.com/6174/comflowy/assets/15819224/09a168c0-7229-488c-97ce-6647c666c054)
`图A` 这个词只出现了一次，我不理解这个 `图A` 是怎么来的？

**Comment by bingwei** [comment]
@HeskeyBaozi 看这里。这个图A标识的不是很清晰
<img width="1052" alt="image" src="https://github.com/6174/comflowy/assets/445377/3c74ab54-6720-4d70-8147-1fe97181df0b">

**Comment by thinkingjimmy** [comment]
因为没有新的反馈，故 issue 关闭。
