### ISSUE TITLE
Feedback for “LoRA”

### ISSUE THREAD

**Issue by maumel** [6174/comflowy#53]
继续使用 LoRA workflow，首先将 Load LoRA 里的模型，切换成 LCM-LoRA。需要注意，这里需要选择跟你的 checkpoint 一致的 LoRA，比如我这用的 checkpoint 是 sdxl，就要使用 sdxl LCM-LoRA。

这里没有讲明白，看不懂是什么意思。
你前面说了下载LCM-LoRA，没有下载sdxl LCM-LoRA啊。怎样才是一致的？没有讲明白

**Comment by thinkingjimmy** [comment]
我在教程最开头，就让下载 LCM-LoRA 了，如果你点击链接就能看到这个模型是sdxl  lcm lora：
<img width="543" alt="image" src="https://github.com/6174/comflowy/assets/37492595/1e11c405-bebe-4c4f-976b-b57789529970">
