### ISSUE TITLE
Feature Request | limitation | enhancement

### ISSUE THREAD

**Issue by kakachiex2** [6174/comflowy#54]
So far I love it specially the UI is beautiful but I found some limitation that make it less useful than ComfyUI.
Where is the Right click menu this is important for fast interaction with node groups, custom color, save workflow etc... lots of option I don't see there; when loading my workflow is a mess, I organize my workflow with groups and color code in groups inside groups. 

This is an example of how workflow can be organized nicely.
![MAPS_Generatro_WF_V1 01](https://github.com/6174/comflowy/assets/1762112/955c64dc-2826-47fc-b7c6-4f1f50c4b075)

- Reroute node don't work or if it's implemented I don't see it only appear wen open a workflow that have it.
- Groups need option to send back or front because groups are disperse in different depth "POSITION" in the UI.
- Reroute need to be smaller it suppose to be for organization.
- In comfyUI group inside group can't be move it only move the master groups it supposed to move groups that are inside groups too this can be a nice feature in comflowy.

https://github.com/6174/comflowy/assets/1762112/9ffbd9d6-0ec0-41d6-b6b5-7577afc5fe49

- comflowy nodes inside groups don't stick to the group.
- Dot background is too dark it suppose to looks like this in chainner

![Screenshot 2024-03-14 004755](https://github.com/6174/comflowy/assets/1762112/b1f1d6bb-0248-471a-bc4a-fbc9d0ce8e02)

- Add right click menu important
- were are the others wire connector style only curve is there.
- Check this proyect have some nice UI similar to comflowy you can install it in comfy and test it is really cool but lacks some features
- https://github.com/canisminor1990/kitchen-comfyui
 
![screenshot-2](https://github.com/6174/comflowy/assets/1762112/433151e0-bc0f-4de7-806d-bce38e5b3241)

I will continue exploring and give feedback, I really like your work beautiful.

**Comment by thinkingjimmy** [comment]
Thank you for your feedback, please continue to use our product, as your feedback is our motivation to keep iterating 😄

1. Our nodes support right-click to quickly adjust colors. Double-clicking can bring up the add node panel. We may support right-click to call up a shortcut menu in the future.
2. Some nodes have compatibility issues. We are working on fixing and supporting these.
3. We will support the Group issue subsequently.
4. Thank you for the feedback on the UI issue; we are also redesigning it.

**Comment by thinkingjimmy** [comment]
Since there has been no further response, this issue is being closed.
