### ISSUE TITLE
Feedback for “安装 ComfyUI”

### ISSUE THREAD

**Issue by Pang-BaiXu** [6174/comflowy#56]
<img width="557" alt="image" src="https://github.com/6174/comflowy/assets/23161429/eabbe48e-6aaf-41cb-8f2a-ee476feac4a9">

**Comment by thinkingjimmy** [comment]
这个应该输入一下 pip install safetensors 就好

**Comment by thinkingjimmy** [comment]
因为没有新的反馈，故 issue 关闭。
