### ISSUE TITLE
界面需要有中文版的

### ISSUE THREAD

**Issue by LiDHong** [6174/comflowy#59]
麻烦界面弄一个中文版的

**Comment by thinkingjimmy** [comment]
新版本应该已经支持界面中文，以及节点中文。

**Comment by LiDHong** [comment]
界面里面支持中文版吗









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "6174/comflowy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月7日(星期天) 下午4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [6174/comflowy] 界面需要有中文版的 (Issue #59)





 
新版本应该已经支持界面中文，以及节点中文。
