### ISSUE TITLE
生成的图片非常模糊，参数跟SD web ui一样

### ISSUE THREAD

**Issue by catch6** [6174/comflowy#63]
换了几个模型都是非常模糊
webui的
<img width="500" alt="image" src="https://github.com/6174/comflowy/assets/15259698/7d1736d5-6d67-439d-b42b-6d712825789f">
comflowy的
<img width="1302" alt="image" src="https://github.com/6174/comflowy/assets/15259698/1104e467-5182-4b05-82ca-a384f719bf5a">

**Comment by catch6** [comment]
种子也保持一致的情况下也不一样，我怀疑我选的模型并没有成功被应用

<img width="689" alt="image" src="https://github.com/6174/comflowy/assets/15259698/b058c0e0-28f9-4469-827e-b2d9d1865123">

**Comment by thinkingjimmy** [comment]
点击右上角 termianl，然后点击 pip install 输入以下命令 torchvision==0.16.2

**Comment by thinkingjimmy** [comment]
因为没有新的反馈，所以关闭此 issue
