### ISSUE TITLE
Every time I start the workflow, an error will be reported

### ISSUE THREAD

**Issue by wizardzzj** [6174/comflowy#65]
Every time I start the workflow, an error will be reported, prompting: "Value not in list", but my file is indeed in the corresponding folder. Although the workflow can be executed and images can be generated, an error will be reported.
![issue](https://github.com/6174/comflowy/assets/54799918/f887bd03-eb89-4cb0-a634-dc111aa70728)
![issue02](https://github.com/6174/comflowy/assets/54799918/46d31f0f-64ef-4b31-b355-f000f373f277)

**Comment by thinkingjimmy** [comment]
Will this error still be reported with the new version?

**Comment by thinkingjimmy** [comment]
The issue is closed because there is no new feedback.
