### ISSUE TITLE
Feedback for “ContrlNet”

### ISSUE THREAD

**Issue by HsiaoJim** [6174/comflowy#7]
ControlNet Scribble：将其放到 ComfyUI 里的 models/controlnet 文件夹内。
ControlNet Openpose: 将其放到 ComfyUI 里的 models/controlnet 文件夹内。
我下载着俩个模型发现是一样的，不确定是否是放重了，还是两者命名一样。

**Comment by thinkingjimmy** [comment]
我看了下链接，没有放重，是命名一样。需要你重新命名一下：
* ControlNet Scribble：https://huggingface.co/lllyasviel/sd-controlnet-scribble/resolve/main/diffusion_pytorch_model.safetensors?download=true
* ControlNet Openpose：https://huggingface.co/lllyasviel/sd-controlnet-openpose/resolve/main/diffusion_pytorch_model.safetensors?download=true

**Comment by HsiaoJim** [comment]
感谢，收益良多。
