### ISSUE TITLE
无法生成图片，只能生成色块

### ISSUE THREAD

**Issue by yangmier** [6174/comflowy#79]
This is about:
- [ ] ComfyUI installation
- [ -] Text to image workflow
- [ ] Image to image workflow
- [ ] Text to video workflow
- [ ] Other

**Problem**

使用默认的工作流只能生成色块，无法生成图片。

**Steps To Reproduce**

Or paste reproducible error codes:

程序未报错，但只能生成色块

**Expected behavior**

文生图

**Screenshots**
<img width="717" alt="image" src="https://github.com/6174/comflowy/assets/133110795/7e3166e5-b590-40a7-8cf8-458e93da7714">

**Environment:**
 - ComfyUI or Comflowyspace version: 
 - 0.1.5
 - OS, if relevant: [e.g. MacOS]
 - MacOS , M1，64 GB RAM

**Comment by yangmier** [comment]
尝试用视频中的解决方案，加载torchversion==0.16.2, 报错如下：

(base) ming@yangmingdembp ComfyUI % /Users/ming/miniconda3/envs/
 install torchversion==0.16.2 
ERROR: Could not find a version that satisfies the requirement torchversion==0.16.2 (from versions: none)
ERROR: No matching distribution found for torchversion==0.16.2

**Comment by thinkingjimmy** [comment]
勘误：视频中的包版本应该是 torchvision==0.16.2

**Comment by tkmerlodi** [comment]
兄弟，你这个问题解决了吗，我出图不是色块，但是颜色有问题，也不知道是什么原因。
![CleanShot 2024-04-27 at 10 10 43@2x](https://github.com/6174/comflowy/assets/111571068/f3b5cea1-add1-47fb-8c14-fa790cbba36a)

**Comment by thinkingjimmy** [comment]
因为没有新的反馈，故 issue 关闭。
