### ISSUE TITLE
kaggle部署第一步拉代码失败

### ISSUE THREAD

**Issue by lys623** [6174/comflowy#8]
![image](https://github.com/6174/comflowy/assets/4364314/ac9cef56-07ba-47b9-a789-3903d8ee8515)

**Comment by thinkingjimmy** [comment]
你是不是没有将 Notebook options 里的互联网开关设置为开？

**Comment by lys623** [comment]
![image](https://github.com/6174/comflowy/assets/4364314/a1fe85cb-0420-42ec-a4dd-c4d08ca8c7ae)
没看见这个选项

**Comment by thinkingjimmy** [comment]
你截图里的 Add tag 下面不是有一行字写了吗？你需要手机号认证才能获得 internet connection

**Comment by thinkingjimmy** [comment]
Fixed： 56b8df8e2037d118d092c17c91d22a3648116c0d

**Comment by lys623** [comment]
> 你截图里的 Add tag 下面不是有一行字写了吗？你需要手机号认证才能获得 internet connection

我去，没留意，谢谢，还是中文比较容易看到
