### ISSUE TITLE
Feedback for “Comflowy 介绍”

### ISSUE THREAD

**Issue by Aaronliu2016** [6174/comflowy#81]
> 欢迎在我们的 Discord 的分享频道分享，，亦或者在 Github 上提交 newsletter Issue一经采纳我们会将其收录到我们的 newsletter 中，让更多的人看到。

小小强迫症一下：这里的逗号应该是错位了，应该是如下这样的吧：

> 欢迎在我们的 Discord 的分享频道分享，亦或者在 Github 上提交 newsletter Issue，一经采纳我们会将其收录到我们的 newsletter 中，让更多的人看到。

**Comment by thinkingjimmy** [comment]
感谢提醒，已修改
