### ISSUE TITLE
Feedback for “ContrlNet”

### ISSUE THREAD

**Issue by cndxflwb** [6174/comflowy#87]
> ControlNet Scribble：将其放到 ComfyUI 里的 models/controlnet 文件夹内。
> ControlNet Openpose: 将其放到 ComfyUI 里的 models/controlnet 文件夹内。

ControlNet Scribble和ControlNet Openpose指向的链接是一样的，是正确的吗？

**Comment by thinkingjimmy** [comment]
不是一个链接，只是文件名一样：
<img width="705" alt="image" src="https://github.com/6174/comflowy/assets/37492595/8fe5bd13-a5ff-4e07-be05-889c9c53aadc">
