### ISSUE TITLE
Feedback for “如何安装 ComfyUI 插件？”

### ISSUE THREAD

**Issue by WilsonServer** [6174/comflowy#88]
抱歉直接使用的中文。ComflowyUI界面非常棒，但是目前版本很多自定义节点不能生效，节点连接上图标太小也有点难选。

**Comment by thinkingjimmy** [comment]
1. 不生效有可能是插件依赖问题
2. 我们最近优化了不少插件，如果遇到真的无法使用，欢迎留言反馈
