### ISSUE TITLE
看别人用sd画的图很好看，怎么知道是用哪个模型呢？比如这个

### ISSUE THREAD

**Issue by lys623** [6174/comflowy#9]
比如下面这个创意文字画的图
![20240102-222116](https://github.com/6174/comflowy/assets/4364314/a41c044c-6bef-43dd-af81-37203f60859e)

如何在ComfyUI的找到这种插件？或者在 HuggingFace？ CivitAI 站点？

**Comment by thinkingjimmy** [comment]
有几种获得的方法：如果这个人做的图是通过 ComfyUI 导出，并携带了 ComfyUI 的 workflow 信息，那就可以通过导入图片的方式获得模型等信息。但如果没有携带，那基本上你只能通过问的方式获得（问作者或者专家），或者你去C站一个个看。

**Comment by lys623** [comment]
> 有几种获得的方法：
> 
> 1. 如果这个人做的图是通过 ComfyUI 导出，并携带了 ComfyUI 的 workflow 信息，那就可以通过导入图片的方式获得模型等信息。
> 2. 但如果没有携带，那基本上你只能通过问的方式获得（问作者或者专家），或者你去C站一个个看。

谢谢，C站是哪个站？域名是什么

**Comment by thinkingjimmy** [comment]
就是你说的 CivitAI
