### ISSUE TITLE
Feedback for “云端安装 ComfyUI”

### ISSUE THREAD

**Issue by jetablezhu** [6174/comflowy#90]
已经没有Notebook Options了，无法选择GPU配置，另外就是运行Installation会报错：fatal: unable to access 'https://github.com/comfyanonymous/ComfyUI.git/'

**Comment by thinkingjimmy** [comment]
改名叫 Session options 了，功能都是一样的。报错是因为你没有开 internet 开关。如果你不懂代码，我建议你不要使用 Kaggle 运行。或者尝试我们的云端版本：comflowy.com
